apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.ovirt.org
  annotations:
      # This CSIDriver is managed by an OCP CSI operator
      csi.openshift.io/managed: "true"
spec:
  attachRequired: true
  podInfoOnMount: false
